### ISSUE TITLE
# ambiguous experimental proteoform identifications

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#442]
A lot of ambiguity is rather hidden - maybe check if different gene names of connected experimentals of "labeled" relations

**Comment by acesnik** [comment]
Could you elaborate? This was clear to me earlier in our discussion, but I'm confused again.

**Comment by lschaffer2** [comment]
Right now, which ever connection reaches the experimental first identifies it and it is marked as identified, but in reality it is ambiguous

**Comment by acesnik** [comment]
I might suggest a label "# Possibly Ambiguous Proteoform Identifications" since some of these cases are really clearly one or the other identification upon inspection, particularly in cases where one path is longer than the other. Otherwise, we could use this to mark identifications that had the same path length from a theoretical -- this would be the edge case of assuming proteoform identifications with shorter paths from the theoretical proteoform are more likely to be correct.

**Comment by lschaffer2** [comment]
I like the point of saying "possibly ambiguous". Right now, path length isn't considered but that might be a nice way to lower the reported number since a shorter path length isn't really as ambiguous as when there's two equal path lengths from 2 different theoreticals
